// ════════════════════════════════════════════════════════════════════════════
//  GALERIE DE CONCERTS — photos du carrousel
//
//  Pour AJOUTER une photo :
//  1. Mets ton image dans le dossier  public/images/galerie/
//  2. Ajoute son chemin dans la liste ci-dessous.
//  Pour RETIRER une photo : supprime sa ligne. L ordre = ordre d affichage.
// ════════════════════════════════════════════════════════════════════════════

export const galerie: string[] = [
  '/images/galerie/01.jpg',
  '/images/galerie/02.jpg',
  '/images/galerie/03.jpg',
  '/images/galerie/04.jpg',
  '/images/galerie/05.jpg',
  '/images/galerie/06.jpg',
  '/images/galerie/07.jpg',
  '/images/galerie/08.jpg',
  '/images/galerie/09.jpg',
  '/images/galerie/10.jpg',
  '/images/galerie/11.jpg',
  '/images/galerie/12.jpg',
  '/images/galerie/13.jpg',
  '/images/galerie/14.jpg',
  '/images/galerie/15.jpg',
  '/images/galerie/16.jpg',
  '/images/galerie/17.jpg',
  '/images/galerie/18.jpg',
  '/images/galerie/19.jpg',
  '/images/galerie/20.jpg',
  '/images/galerie/21.jpg',
  '/images/galerie/22.jpg',
  '/images/galerie/23.jpg',
  '/images/galerie/24.jpg',
  '/images/galerie/25.jpg',
  '/images/galerie/26.jpg',
  '/images/galerie/27.jpg',
  '/images/galerie/28.jpg',
  '/images/galerie/29.jpg',
  '/images/galerie/30.jpg',
  '/images/galerie/31.jpg',
  '/images/galerie/32.jpg',
  '/images/galerie/33.jpg',
  '/images/galerie/34.jpg',
  '/images/galerie/35.jpg',
  '/images/galerie/36.jpg',
  '/images/galerie/37.jpg',
  '/images/galerie/38.jpg',
  '/images/galerie/39.jpg',
  '/images/galerie/40.jpg',
  '/images/galerie/41.jpg',
  '/images/galerie/42.jpg',
  '/images/galerie/43.jpg',
  '/images/galerie/44.jpg',
  '/images/galerie/45.jpg',
  '/images/galerie/46.jpg',
  '/images/galerie/47.jpg',
  '/images/galerie/48.jpg',
  '/images/galerie/49.jpg',
  '/images/galerie/50.jpg',
];
